sudo: required

matrix:
  include:
    - language: go
      go: 
        - 1.9

    - language: bash
      services:
        - docker
      script:
        - go get github.com/prometheus/client_golang/prometheus
        - go get github.com/prometheus/client_golang/prometheus/promhttp
        - go get github.com/prometheus/common/log
        - go get github.com/prometheus/common/version
        - go build -ldflags '-d -s -w' -a -tags netgo -installsuffix netgo fluentd_exporter.go
        - docker build -t vect0r/fluentd_exporter .
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
          docker push vect0r/fluentd_exporter;
          fi

notifications:
  email:
    - "$EMAIL"
